---
# Copyright (c) 2021 Oracle and/or its affiliates.
# All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl
# 
# Purpose: Orchestrator of multiple roles


- name: Calling roles required for OS Standard Configuration
  block:
    - include_role:
        name: lnx_osutils
    - include_role:
        name: lnx_add_dummy_user

