# Copyright (c) 2021 Oracle and/or its affiliates.
# All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl
# 02_pv.yaml
#
# Purpose: File that handles the creation of a persistent volume inside Kubernetes Cluster

apiVersion: v1
kind: PersistentVolume
metadata:
 name: wp-oke-fsspv
spec:
 storageClassName: oci-fss
 capacity:
  storage: 100Gi
 accessModes:
  - ReadWriteMany
 mountOptions:
  - nosuid
 nfs:
# Replace this with the IP of your FSS file system in OCI
  server: 10.0.2.32
# Replace this with the Path of your FSS file system in OCI
  path: "/endevourwordpress"
  readOnly: false